version: '2'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}    
  myapp:
    image: docker.io/bitnami/symfony:6.3
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=${MYSQL_USER}
      - SYMFONY_DATABASE_NAME=${MYSQL_DATABASE}
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
